### ISSUE TITLE
Add zip_longest built-in

### ISSUE THREAD

**Issue by fredcallaway** [evhub/coconut#105]
These two libraries are very commonly used, especially in a functional style. Most programmers know what these functions/classes do and where they are implemented, and both modules have a negligible import time.

**Comment by evhub** [comment]
Both modules are imported already, actually. Coconut uses them to power many of its features:
- `data` statements use `collections.namedtuple`
- pattern-matching uses `collections.abc` (for implicit type-checking)
- `consume` uses `collections.deque`
- iterator slicing (`$[]`) uses `itertools.islice` (but only very minimally, Coconut's iterator slicing is much more complex)
- iterator chaining (`::`) uses `itertools.chain.from_iterable` (combined with Coconut's lazy list compilation)
- `itertools.takewhile` is provided as a built-in under the name `takewhile`
- `itertools.dropwhile` is provided as a built-in under the name `dropwhile`
- `itertools.tee` is provided as a built-in under the name `tee`

Therefore, since Coconut already provides so much of the functionality contained within them, providing them as built-ins themselves wouldn't add very much, and it would encourage programmers to use worse versions of some features (e.g. using `itertools.islice` instead of `$[]` iterator slicing, which is much less efficient).

Thus, I won't be adding `collections` and `itertools` as built-ins, however, if there are tools in them that you think are really useful that I haven't yet brought into Coconut, definitely tell me and that would definitely be something I'd be willing to consider. Thanks for the issue, though!

**Comment by fredcallaway** [comment]
I agree that * importing the entire modules would be too much. Here are the ones I use regularly. The marked ones are especially useful.

```
defaultdict  # !!
OrderedDict  # !!
deque
Counter

product
permutations
combinations
combinations_with_replacement
accumulate
groupby # !!

**Comment by evhub** [comment]
@fredcallaway My current thinking is that unless there are optimizations I can make to the functions in `itertools` (e.g. Coconut's built-in `tee` is faster in many cases than `itertools.tee`), I'm probably going to default to just having people do `from itertools import ...` instead of bringing it in for them. To that end, however, I'm going to go over your list and see if there are any similar optimizations I can make to those functions, and if so, then I'll consider bringing them in as built-ins as well.

**Comment by fredcallaway** [comment]
You may be interested in this project:

https://github.com/pytoolz/cytoolz

It implements many useful functional and list processing utility functions in Cython.

**Comment by evhub** [comment]
@fredcallaway Thanks! I'll definitely take a look at that.

**Comment by bj0** [comment]
one function I find myself defining often is:

    def flatmap(func, *iterables) = map(func, *iterables) |> chain.from_iterable

**Comment by evhub** [comment]
@bj0 That's actually a very good candidate to add as a built-in. Although there does exist an even simpler definition currently of
```
flatmap = (::)..map
```

**Comment by bj0** [comment]
Ah, neat!

**Comment by evhub** [comment]
`zip_longest` is now added on `coconut-develop` as an enhanced version like `zip`. I've chosen not to add `flatmap` as there aren't really any enhancements to make there and `flatmap` is easily definable in one line as noted previously.

**Comment by aananko** [comment]
> will work, since `(::)` is just `chain.from_iterable`

This seems to be not true anymore. (::) looks more like `chain` than `chain.from_iterable` :

**Comment by evhub** [comment]
@aananko I've moved this to #582. It does seem that at some point `(::)` got changed from `chain.from_iterable` to just `chain` and I don't remember why.

**Comment by evhub** [comment]
As of `coconut-develop>=1.5.0-post_dev58`, Coconut now has a `flatten` built-in—if you want `flatmap`, it's now just `flatten..map`.
