### ISSUE TITLE
Support tail call optimization without requiring a decorator

### ISSUE THREAD

**Issue by darkf** [evhub/coconut#115]
Requiring the programmer to annotate tail recursion with `@recursive` is a bit awkward for a language that isn't Python. It should be able to analyze the function and perform it automatically.

**Comment by evhub** [comment]
Definitely a good suggestion. I'll work on it for the next version.

**Comment by evhub** [comment]
@darkf I've been investigating this and my concern is that, if the recursion doesn't go very deep, it's actually much faster to not try to apply tail recursion optimization--it only becomes faster when the number of recursive calls gets very large, and that's not something the compiler can figure out, only the programmer.

**Comment by darkf** [comment]
@evhub Is it not possible to turn tail calls into while loops, rebinding the arguments when a tail call is otherwise performed? (It's OK to not optimize forms like `def f(): x = f; return x()`, but direct calls to `f`.)

**Comment by chuckwondo** [comment]
@evhub If you implement automatic TCO, then I suggest what you do with the `@recursive` decorator is use it as a double-check. That is, if a function is decorated with `@recursive` and the function is actually _not_ tail recursive, then issue a compiler warning.

This is how the `@tailrec` annotation in Scala works. The Scala compiler will automatically perform TCO where possible, but where it is not possible for functions/methods marked with the `@tailrec` annotation, the compiler will issue a warning.

Also, perhaps you want to consider deprecating `@recursive` and defining a new decorator named `@tailrec` (like Scala), which is arguably more accurate given that not all recursive functions are _tail_ recursive. That is, `@recursive` is perhaps too broadly named.

**Comment by evhub** [comment]
@chuckwondo Those are both great suggestions. My concern with having `@recursive` raise an error if the function wasn't automatically TCO'd is what happens when a function is tail recursive, but there's no way to tell that (e.g. cases like `def f(): x = f; return x()`). Most of those cases can probably be refactored (that example obviously can), but I'm loathe to just assume that. As for renaming `recursive`, I agree that something like `tail_recursive` would probably be better, and I'll probably try to do something like that for the next release.

**Comment by chuckwondo** [comment]
@evhub You could have the compiler raise a warning, not an error, as does the Scala compiler. Further, if the function wasn't automatically TCO'd because the compiler wasn't able to tell (as in your example), then I'd argue that that is precisely a case for issuing a compiler warning.

In other words, regardless of why the compiler was unable to perform TCO on a function decorated with `@recursive` (or possibly `@tail_recursive` in the future), the point is exactly that: the developer marked it as tail recursive, but the compiler was unable to perform TCO on it.

Whether the function truly is _not_ tail recursive, or the compiler simply cannot tell (yet), the developer is warned that the compiler could not perform TCO on it, and therefore must either refactor the function, or be willing to live with the possibility of blowing out the stack.

By issuing a compiler warning (not an error), you make the developer aware of the potential problem, yet still give the developer a choice: either ignore the warning and suffer the possible consequences, or change the code.

Of course, if the developer chooses to change the code, and is unable to refactor it into something the compiler can TCO, the final change might simply be to manually perform TCO (but hopefully that's not necessary).

**Comment by evhub** [comment]
@chuckwondo I completely agree--I think issuing a warning is exactly the correct behavior--I'm not sure why I didn't think of that earlier. That's almost certainly what I'll do. And thanks! I'm glad you're enjoying working with Coconut.

**Comment by evhub** [comment]
@chuckwondo See #141 for the migration strategy of changing `recursive` to `tail_recursive`.

**Comment by chuckwondo** [comment]
@evhub Sounds good!

**Comment by evhub** [comment]
New problem I just realized when I went to implement this: I can easily do automatic TCO on this
```
def func(x):
 return func(x)
```
but I don't have a good way to detect this
```
def func(x):
 if ...:
  return func(x)
 else:
  return func(x)
```
even though it also should be TCO'd.

**Comment by chuckwondo** [comment]
Yes, I think you'll need to do the parsing like you said. However, you may need to broaden things slightly in that it is not necessary for the tail call to be part of a `return` statement. Granted, that is arguably the vast majority of cases, but it's not a necessity.

It is possible that someone has implemented a tail-recursive "procedure" that does not explicitly return a value, such as a tail-recursive "apply" type of function that, for example, walks a tree and performs an operation on each node, using side effects rather than returning values.

**Comment by darkf** [comment]
Yes, you need to do control flow analysis on it to see if calls are actually in a tail position.

**Comment by evhub** [comment]
@chuckwondo @darkf Yep, that's the plan.

**Comment by evhub** [comment]
Another thing I'd like to make sure I get done with this: any form of a tail call, not just tail recursion, should be optimized.

**Comment by evhub** [comment]
@darkf @chuckwondo This is should now be working on the `develop` branch, and will be included in the next release.
