### ISSUE TITLE
CoconutWarning: missing new line at end of file (line 1)

### ISSUE THREAD

**Issue by RichterL** [evhub/coconut#187]
Wrote first hello world file but got this warning. Where have I gone wrong?

**Comment by evhub** [comment]
@RichterL It's only a warning, so Coconut should still run anyway, but if you want to make the error go away, just add a blank line to the end of your file. That is, instead of
```
"hello, world" |> print
```
you need
```
"hello, world" |> print

```
For context on why ending all files with a new line is important, see [this StackOverflow thread](http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).
