### ISSUE TITLE
mingw64 coconut cmd hangs

### ISSUE THREAD

**Issue by marawuti** [evhub/coconut#215]
I've installed coconut via pip on my mingw64 running under Windows 10.

@@ 508 > coconut -v
Version 1.2.0 [Colonel] running on Python 3.5.2 (default, Nov 7 2016,
14:06:02) [GCC 6.2.0 64 bit (AMD64)]

but 
@@ 509 > coconut

hangs.

What debugging approach can I use to provide useful data?

**Comment by evhub** [comment]
@marawuti Can you try passing the `--verbose` flag, and see if you get any output then? If that doesn't work, try installing the current `develop` version instead of the current release version using `pip install coconut-develop`, then paste in both the install log and the result of running `coconut --verbose` after the installation finishes.

**Comment by evhub** [comment]
This error was being caused by the same issue in these stack overflow threads regarding Python on CygWin:

- <http://stackoverflow.com/questions/13588454/invoking-python-under-cygwin-on-windows-hangs>
- <http://stackoverflow.com/questions/3250749/using-windows-python-from-cygwin>

However, I have added a workaround that should hopefully help alleviate the problem, even if none of the solutions in those threads is taken. For future reference, the best, easiest solution seemed to be to run `cygstart coconut` instead of just `coconut`.
