### ISSUE TITLE
Match dicts with extra keys

### ISSUE THREAD

**Issue by cgarciae** [evhub/coconut#267]
`dict`s that have all the requiered keys should match, even if they have more keys. Currently the following code gets a `MatchError`:

```python
def test({"a": a} as d):
    print(a, d)

dict(a = 2, b = 3) |> test
```
This behaviour is found in Elixir and Elm, and I think it would be nice to have it in Coconut.

**Comment by evhub** [comment]
@cgarciae I like the idea, but I think there should be a special syntax for it.

If we use [PEP 448](https://www.python.org/dev/peps/pep-0448/) syntax for this, we could have:
```python
{"a": a, **rest} = {"a": 2, "b": 3}
assert rest == {"b": 3}
```
Or to do what you want, we could rewrite it as:
```python
def test({"a": a, **_} as d):
    print(a, d)

dict(a=2, b=3) |> test
```

Right now, Coconut pattern-matching supports some of PEP 448, but not all of it. I think my plan for how to resolve this will be to add full PEP 448 support to pattern-matching, which will also mean that PEP 448 syntax will become available on all versions without the need for `--target 3.5`, as is currently the case.

**Comment by cgarciae** [comment]
@evhub Like your proposal, I was also thinking there should be a way to get the "rest" of the dict so your solution covers all cases. Look forward to it :)

**Comment by cgarciae** [comment]
@evhub BTW: this would really clean some of my code. Give me a heads up where ready for testing!

**Comment by evhub** [comment]
@cgarciae This is ready for testing in `develop`!

**Comment by evhub** [comment]
@cgarciae @puruzio This has now been implemented in `develop`! Just `pip install coconut-develop` to get the new behavior.

Still not supported for destructuring assignment, since this has been implemented using pattern-matching, which has subtle differences from PEP 448, so if you want it there you have to specify you're using pattern-matching by putting `match` at the front.

For full PEP 448 support across all targets in Coconut, I've raised the separate issue #289.
