### ISSUE TITLE
Add reiterable built-in

### ISSUE THREAD

**Issue by pchampin** [evhub/coconut#271]
I am not an expert in functional programming. That being said, it seems to me that the notion of "lazy list" in coconut is significantly different from their counterpart in *e.g.* Haskell.

Consider the following function (and the associated micro test-suite below):
```python
def list_type(xs):
    case xs:
        match [fst,snd]::tail:
            return "at least 2"
        match [fst]::tail:
            return "at least 1"
        match (| |):
            return "empty"

assert list_type((|1,2,3,4,5|)) == "at least 2"
assert list_type((|1,2,3,4|)) == "at least 2"
assert list_type((|1,2,3|)) == "at least 2"
assert list_type((|1,2|)) == "at least 2"
assert list_type((|1|)) == "at least 1"  # this test fails, we get "empty"
assert list_type((| |)) == "empty"
```

The penultimate test fails, because the first ``match`` clause *consumes* the first item of the iterator. I did test an equivalent function in Haskell, and it works as expected. So there is a mismatch here between Coconut and Haskell in how they use pattern matching. My understanding is that pattern matching is more appropriate for immutable values, and iterators are definitely mutable.

This divergence between Haskell (and, AFAIK, other functional languages) and Coconut, can be considered either a bug or a feature...

If it is considered a feature, then I would suggest to put a warning message in the documentation, and examples of *do's* and *dont's* when using ``case`` statements for iterators... and possibly replacing the name "lazy list" with something else. It is bound to confuse people with a background in functional programming. And I would argue that it may also confuse Python programmers with no such background, because a *list* is, in general, something more "stable" than an iterator.

I would lean towards considering this as a bug, though. Lazy lists as *immutable* values are closer to what other functional languages use, and open space for more optimizations... But I understand that this would be a heavy change in the language...

**Comment by evhub** [comment]
@pchampin There are really two separate issues here.

First, as you mention, lazy lists are mutable. The reason for this is that lazy lists are implemented as Python iterators, which have to be mutable, since the way you access their elements is via repeated calls to `next`, which requires a state change after every `next` call. It is possible to change this and implement lazy lists as custom iterables instead, however that could potentially introduce a lot of overhead.

Second, iterator pattern-matching is non-preserving. The pattern-matching machinery you are using is built to work on arbitrary iterators, not just lazy lists, so this is really a separate issue. Technically, this is documented behaviour, but the only documentation is a tiny note in the [semantic specification](http://coconut.readthedocs.io/en/master/DOCS.html#semantic-specification) section of the `match` documentation. Iterators, which only support `next` as a means of getting new values, aren't very amenable to immutability, since if you want to make them immutable you have to store the result of every `next` call you make in case someone else wants to make the same call. The function that does that for you is [`tee`](http://coconut.readthedocs.io/en/master/DOCS.html#tee), and the reason it's a Coconut built-in is for exactly this use case. Using `tee`, we could rewrite your example above as:
```python
def list_type(xs):
    xs1, xs2, xs3 = tee(xs, 3)
    match [fst,snd]::tail in xs1:
        return "at least 2"
    match [fst]::tail in xs2:
        return "at least 1"
    match (| |) in xs3:
        return "empty"
```
which I agree is hardly ideal. Here are some possible resolutions, however:

1. Just make the documentation better and tell people to use `tee` if they want to make multiple matches against the same iterator.
2. Add a new `case iter` statement (or some other new name) which automatically creates tees of the input iterator against every match. Solves your use case really nicely, but doesn't necessarily generalize to other use cases. Your example would become:
```python
def list_type(xs):
    case iter xs:
        match [fst,snd]::tail:
            return "at least 2"
        match [fst]::tail:
            return "at least 1"
        match (| |):
            return "empty"
```
3. Have `case` detect when it is passed an iterator and automatically creates tees as for `case iter`. The only solution that makes your code work as is, but adds an extra (potentially expensive) check to every invocation of `case`.
4. Have all pattern-matching detect when it is matching against an iterator and `tee` it. This is the most complete, straightforward solution, but it introduces a huge amount of overhead if you don't ever plan to use that tee.
5. Add a new `match tee` statement (or some other new name) that automatically tees its input before matching against it. Not as nice in your use case, but potentially more generalizable. Your example would become:
```python
def list_type(xs):
    case iter xs:
        match iter [fst,snd]::tail:
            return "at least 2"
        match iter [fst]::tail:
            return "at least 1"
        match iter (| |):
            return "empty"
```

**Comment by pchampin** [comment]
I gave this some thought... I can live with the current ``case`` statement, and the fact that ``[head]::tail`` consumes the given iterator if it is a plain iterator.

What bothers me more is the use of the ``tee`` function in this context; and the multiple copies of the iterator that you have to use in the different ``match`` clauses... I find it not very pythonic: it lacks elegance (no offense), and makes the code harder to maintain: the order of the ``match`` clauses matters more than it should; if I want to add another ``match``, I have to alter the call to ``tee``...

I propose the following:
```python
def test_type(xs):
    xs = reiterable(xs)
    case xs:
        match (| |):
          return "empty"
        match [x1,x2]::tail:
          return "at least 2"
        match [x1]::tail:
          return "at least 1"
```

The ``reiterable`` function wraps ``xs`` to ensure that you can call ``iter(xs)`` multiple times, and get each time a new iterator that will yield all the values initially "contained" in ``xs``.  This makes it possible to use a ``case`` statement. This also makes it less sensitive to order (the "empty" can be first -- of course, the "at least 2" must still come before "at least 1").

I did implement the ``reiterable`` function: https://github.com/pchampin/py_reiterable .
Let me know what you think..

**Comment by evhub** [comment]
@pchampin I like that idea a lot! I think that's a very elegant way to resolve the issue here. I definitely think `reiterable` should be added as a Coconut built-in to fix this issue. If you'd like to submit a PR to make that happen, that'd be great! Otherwise, I'll definitely take a go at it myself to get that in the next release.

**Comment by pchampin** [comment]
@evhub I'm glad you like it :) Unfortunately, I don't have the time to delve into the inners of Coconut in order to integrate ``reiterable`` there, but feel free to copy-paste the code and reuse it as you see fit.
