### ISSUE TITLE
Can you add an example for writing a package in Coconut?

### ISSUE THREAD

**Issue by salimfadhley** [evhub/coconut#274]
I'd like to use Coconut to write a redistributable Python package, one that can be hosted on PyPi and installed by other Python developers. 

Is there an example of such a package?

**Comment by evhub** [comment]
@salimfadhley Since Coconut just compiles to Python, releasing a Coconut package on PyPI is exactly the same as releasing a Python package, with an extra compilation step. Just write your package in Coconut, run `coconut` on the source code, and upload the compiled code to PyPI. You can even mix Python and Coconut code, since the compiler will only touch `.coco` files. If you want to see an example of a PyPI package written in Coconut, including a [Makefile](https://github.com/evhub/pyprover/blob/master/Makefile) with the exact compiler commands being used, check out [pyprover](https://github.com/evhub/pyprover).

**Comment by ArneBachmann** [comment]
The missing piece is still a `setup.py` that works without external make tools.
I think calling the coconut interpreter from inside `setup.py` is probably the best you can do.
The original attempt of hooking into `setuptools`' build process failed for me:
```Python
from setuptools import setup
from setuptools.command.build_py import build_py  # to override/extend te build step


class BuildPyCommand(build_py):
  def __init__(_): print("Initializing Coconut builder")

  ''' Transpile coconut code down to python, prior to remaining commands. '''
  def run(_):
    print("Compiling *.coco sources")
    sources = [f for f in os.listdir(".") if f.lower().endswith(".coco")]  # TODO use walk to recursively compile *.coco
    print("Processing sources: %r" % sources)
    for file in sources:
      with open(file, "r") as fc:  # would be great to be using Coconut's with (resource1, resource2) syntax here, but can't run setup.coco with coconut-run
        print("Building %r" % file)
        with open(file[:-5] + ".py", "w") as fp:
          fp.write(coconut.convenience.parse(fc.read(), "file"))  # or "sys" (the default)
    setuptools.command.build_py.build_py.run(_)  # call default build operation

  # This is for debugging, but seems to never get called
  def __call__(_, *args, **kwargs): print((args, kwargs))
  def __getattribute__(_, a): print(a)
  def __getattr__(_, a): print(a)


setup(
  cmdclass = {'build_py': BuildPyCommand}  # redirect build command
)
```
But nothing happens when running `python setup.py build`:
```
running build
```

**Comment by ArneBachmann** [comment]
Here the working verson:
```Python
# This setup script requires "pip install pbr"

import os
from setuptools import setup
import coconut.convenience


print("Compiling *.coco sources to *.py sources")
sources = [f for f in os.listdir(".") if f.lower().endswith(".coco")]  # TODO use walk to recursively compile *.coco
for file in sources:
  if os.stat(file)[8] <= os.stat(file[:-4] + "py")[8]: continue  # ignore up to date files
  with open(file, "r") as fc:  # would be great to be using Coconut's with (resource1, resource2) syntax here, but can't run setup.coco with coconut-run
    print("Building %r" % file)
    with open(file[:-4] + "py", "w") as fp:
      fp.write(coconut.convenience.parse(fc.read(), "file"))  # or "sys" (the default)


setup(
  setup_requires = ['pbr'],  # , 'd2to1' #  d2to1=True,
  pbr = True  # ensures the use of sane defaults and information from setup.cfg, requirements.txt and Git
)
```

**Comment by evhub** [comment]
@ArneBachmann I would highly recommend you just compile before you upload, that way you're distributing the compiled Python, not the Coconut source, but if you really want to compile in your `setup.py`, you should use `coconut.convenience.cmd`, not `coconut.convenience.parse`. Thus, I would do
```
import os.path
from setuptools import setup
from coconut.convenience import cmd

cmd([os.dirname(__file__)])

setup(...)
```
