### ISSUE TITLE
Swap default behavior for running vs. compiling  code

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#287]
I think `coconut file.coco` should not only do a source to source transformation, but by default also run the code (probably without writing the intermediate `file.py` (danger of writing over existing real Python code)), just like `python file.py` compiles and runs the code (which, however, most often leaves the `file.pyc`or `file.pyo`, which is another topic).

The use of `-r` should be replaced by something like `--transpile-only` (or abbreviation thereof), which would resemble the current default behavior, while leaving out the option would mimic the current `-r`behavior.
What do you think?

**Comment by evhub** [comment]
@ArneBachmann You're looking for the `coconut-run` command, which behaves just like the `python` command does. See [Coconut Scripts](http://coconut.readthedocs.io/en/master/DOCS.html#coconut-scripts).

The only thing `coconut-run` doesn't do that you suggest is that it does write an intermediate `file.py`, the reason being that then the code doesn't have to be recompiled every time it's run, since Coconut can read it out of `file.py`. If you don't like that behavior, you can pass `--no-write` (`-n`) to disable writing `file.py`. So, the command you'd want to use, then, would be `coconut-run -n file.coco`, which should do what you want.

As for changing the default behavior, 1) I want to keep the CLI backwards-compatible, and 2) this is exactly what `coconut-run` is for, since that is exactly what it's default behavior is. That being said, I think I will definitely try to make `coconut-run` more visible, since right now it's only documented in that one section in the documentation.

**Comment by ArneBachmann** [comment]
Thanks!
