### ISSUE TITLE
Failure to Install in Pythonista

### ISSUE THREAD

**Issue by iamrecursion** [evhub/coconut#288]
Pythonista is an app for working with python on iOS and I was hoping to bring some of my favourite functional programming goodness to it! However, install via `StaSh` (a shell for pythonista which emulates pip) fails with the following error:

```
ImportError('No module named requirements',)
```

I suspect this is an issue down to some issues with `StaSh`, but I thought I might bring it up in any case just in case. 

I'd love to get it working, so if you can think of anything that I can experiment with to do so I'm very happy to try!

**Comment by evhub** [comment]
@iamrecursion Hmmmm... interesting! Probably a result of StaSh not properly emulating `pip`. If their `pip` implementation works for some packages, though, theoretically we should be able to get it to work for Coconut as well. Unfortunately, I don't have an iOS device to replicate this on, so it'd be great if you could try a couple of things to help me out.

First, just to see if this fixes it, try installing `coconut-develop` instead of `coconut`. Some of the way Coconut's packaging works has changed in `develop`, so it'd be great to see if the same error appears there, or if it's slightly different, or if there's no error at all.

Second, it'd be really nice to have a full traceback, not just the `ImportError` message. I don't know enough about StaSh to know how to get that, but if you do, that'd be super useful.

**Comment by iamrecursion** [comment]
You're likely right! It works for the majority of packages that I've installed, though this is one of the more annoying issues I've run into with it. 

I should start by correcting myself. The error mentioned in the first post is for `coconut-develop`, where standard `coconut` produces a different error (as follows), but `pip` (in StaSh) uses 'directory guessing' and appears to think it installs correctly.

```
TypeError('__trunc__ returned non-Integral (type OmniClass)',)
```

I should mention that though it seems to install correctly `coconut -h` returns `coconut: command not found`. Perhaps the main start script is nowhere on `$PATH`. Most scripts that install an 'executable command' have it put into a user `bin` location on `$PATH` but this didn't happen here, probably due to the install not working properly. 

Back to looking at `coconut-develop`, the error output comes from within the `pip` emulation and even enabling traceback in StaSh doesn't give me any more information as it's not an actual crash, but the `pip` emulation just writing diagnostics to `stderr`. For some reason, however, the error has changed:

```
ImportError('cannot import name package_name',)
```

**Comment by evhub** [comment]
@iamrecursion How strange. Well, first, if you can get Coconut to install at all, even if it doesn't add a `coconut` script for some reason, you should be able to run Coconut directly with `python -m coconut`, so hopefully that provides you with a temporary solution. I'll keep digging into this and see if I can figure out what's causing it, though, so we can find something more permanent.

**Comment by iamrecursion** [comment]
Unfortunately that doesn't appear to work, producing the following error:

```
ImportError: No module named coconut.__main__; 'coconut' is a package and cannot be directly executed
```

I suspect there is something more deeply wrong here, likely on the end of StaSh, as inspecting the install directory visually shows that there is most certainly a `__main__.py`. Hopefully I can shine some light on it tomorrow.

**Comment by evhub** [comment]
@iamrecursion Oh, I see--you're running Python 2.6. In that case, instead of `python -m coconut`, you need to do `python -m coconut.main`. The ability to execute Python packages directly (via `__main__.py`) was added in 2.7.

Theoretically, Coconut should support 2.6, but it's always been the version under which it has the most problems. If you have the ability to switch to 2.7, that might fix some of your issues. 2.6 is officially supported (and tested against), so it's still a bug if something isn't working under it, but switching versions might be another temporary solution.

**Comment by iamrecursion** [comment]
Strangely enough the interpreter it's trying to run is actually `Python 2.7.12 (default, Nov 20 2016, 12:12:11)`, though the use of Python 2 is a limitation of StaSh more than anything else. I think the issue may actually be arising from the...somewhat hellish nesting of Python going on with StaSh. It's a python script running on top of the 2.7.12 interpreter (even though 3.5 is available), that uses a script called `python.py` (which internally uses `runpy`) to run the passed in script. 

In any case, an almost identical error arises:
```
ImportError: No module named coconut.main
```

I think this is a deeper issue due to the inherently hacky nature of what's going on inside StaSh for it to run within Pythonista. I'm flagging a bit now, so I'll continue to look into it tomorrow! 

I wouldn't usually care this much, but it's quite fun to hack together little utilities on the go! Coconut is by far the best thing I could have in that regard, given I much prefer functional programming as a paradigm!

**Comment by evhub** [comment]
@iamrecursion I'm glad you enjoy using Coconut! It's really strange that you're getting an `is a package and cannot be directly executed` error on 2.7, that seriously shouldn't happen. I'll see if I can duplicate this by running StaSh locally on my machine (even though that's not supposed to be how it's run), and if I can, I'll try to find a way to fix it.

**Comment by iamrecursion** [comment]
It's very strange, yeah. I'm planning on having a look today as well: I'll let you know what I find.

For running StaSh locally you might want to create a sandbox and install it using the python shell as specified in the [installation](https://github.com/ywangd/stash#installation) portion of the readme. That would likely present the most similar environment to Pythonista for it to run in.

**Comment by iamrecursion** [comment]
Sorry, I fat-fingered that on my phone. To update the situation. 

I've put some tracing in the `pip` emulation used by StaSh and I can now give you a proper error trace for that exception:
```
File "site-packages/stash/bin/pip.py", line 494, in run
    return ArchiveFileInstaller._run_setup_file(setup_filename)
  File "site-packages/stash/bin/pip.py", line 575, in _run_setup_file
    exec (codeobj, namespace, namespace)
  File "/private/var/mobile/Containers/Data/Application/5428F75D-078C-47BF-BD6C-6459FE62408B/tmp/85a61b3ad2584378833e9ea276744423/coconut-develop-1.2.3.post0.dev14/setup.py", line 38, in <module>
    from coconut.requirements import requirements, extras
ImportError('No module named requirements',)
```

Hopefully that sheds some more light on what might be going on.

**Comment by evhub** [comment]
@iamrecursion I believe this has been fixed! Try 1) restart Pythonista, 2) `pip remove coconut` and `pip remove coconut-develop` to purge any old improperly installed versions, and 3) `pip install coconut-develop`.

**Comment by iamrecursion** [comment]
I can confirm that it now installs properly! What was the fix?

Out of my own curiosity, do you have any issues for first time contributors? I'd love to get involved with coconut's development!

**Comment by evhub** [comment]
@iamrecursion Great! Major problem was that Pythonista/StaSh was using a really outdated `setuptools`, and Coconut was relying on some newer, fancier `setuptools` features. Basically, I added some fallbacks in case that fancy stuff fails.

And yeah, there are lots of issues that you should be able to get started on! First, you'll want to check out the [Contributing Guidelines](http://coconut.readthedocs.io/en/develop/CONTRIBUTING.html), then look through Coconut's [open issues](https://github.com/evhub/coconut/issues) for any you might want to try, particularly those marked "contributor friendly," since that means it's something I think (though I could be wrong) shouldn't be that bad for first-time contributors. And, if you have any questions at all, don't hesitate to ask on [Gitter](https://gitter.im/evhub/coconut)!

**Comment by iamrecursion** [comment]
Sounds great! Thanks for being so responsive on this. I'll definitely take a look and find something to work on.
