### ISSUE TITLE
Mypy error

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#317]
```
def daysinyear(year:int) -> int = sum([calendar.monthrange(year, month)[1] for month in range(1, 12 + 1)])
```
Works fine without mypy, but using the `--mypy` option I get
```
error: Iterable expected
error: Iterable[int] has no attribute "next"
```
any idea?

**Comment by evhub** [comment]
@ArneBachmann What you're seeing is MyPy telling you your types are invalid; in this case, that's definitely a bug, since your types are valid. I believe this is a combination of a Coconut issue and a MyPy issue. I have just fixed the Coconut issue, but the MyPy issue won't be fixed until https://github.com/python/mypy/pull/3132 is released, though that should be pretty soon.

**Comment by ArneBachmann** [comment]
Great, thanks!

**Comment by evhub** [comment]
@ArneBachmann This should be fixed on the latest `coconut-develop`!
