### ISSUE TITLE
Auto-transpile dependencies

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#320]
I just noticed, that a python import on another `*.coco` file will fail unless it was transpiled (manually) via coconut before, because the matching `*.py` is missing. Can we add a logic to the transpiler that detects import statements (of all flavors) as actually attempting to import `*.coco` files that need to be transpiled as well to be available for import during runtime?

Currently one would need some kind of build/make process for projects to work correctly after being checked out, because coconut-run on the main file won't suffice.

**Comment by evhub** [comment]
@ArneBachmann The recommended way to distribute Coconut projects is to distribute them as Python, which is why this is the case. That being said, I can see the argument for having imports be automatically compiled if you're using `coconut-run`, since the point of `coconut-run` is to let you execute Coconut scripts directly. I'll keep this open and see what I can do.

**Comment by auscompgeek** [comment]
Why not have some sort of import hook that always lets you import `*.coco` files, as long as coconut has been imported? Both [dg](https://pyos.github.io/dg/) and [hy](http://docs.hylang.org) do this as well.

**Comment by evhub** [comment]
@auscompgeek Yup, that's probably what I'm going to do here!

**Comment by evhub** [comment]
@ArneBachmann @auscompgeek This is now live in `coconut-develop`!
