### ISSUE TITLE
Support cross-Python enums

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#352]
Currently it's part of the P3 standard library.
Current solutions: https://pypi.python.org/pypi/enum/0.4.6
or simply use
```
class Materials:
    Shaded, Shiny, Transparent, Matte = range(4)

>>> print Materials.Matte
3
```
(via https://stackoverflow.com/questions/702834/whats-the-common-practice-for-enums-in-python)

**Comment by ArneBachmann** [comment]
Seems to be more complex... You not only want to compare via `v == Enum.Variant` but also have a decent `__str__`, and probably allow comparison via `is`...
Thus all enum variants need to be some kind of object that is able to output the full enum name.

**Comment by ArneBachmann** [comment]
Something like
```
class Enum(object):

  class Variant(object):
    def __init__(_, enum, name, value): _.enum = enum; _.name = name; _.value = value
    def __str__(_): return _.enum + "." + _.name
    def __repr__(_): return "enum<" + _.enum + "." + _.name + ">"

  def __init__(_, name, *args, **kwargs):
  	_.name = name
  	for variant in args: _.__dict__[variant] = _._variant(variant)
  	for variant, value in kwargs.items(): _.__dict__[variant] = _.variant(variant, value)
  def __str__(_): return _.name
  def __repr__(_): return "enum<" + _.name + ">"
  def _variant(_, name, value = None): return Enum.Variant(_.name, name, value)

Car = Enum("Car", "A", "B")
c = Car.B
print(Car)
print(Car.A)
print(repr(Car))
print(repr(Car.A))
print(c == Car.A)
print(c == Car.B)
print(type(Car))
print(type(c))

Car
Car.A
enum<Car>
enum<Car.A>
False
True
<class '__main__.Enum'>
<class '__main__.Variant'>
```

**Comment by evhub** [comment]
How about:
```python
data CarA
data CarB
Car = CarA, CarB

c = CarA()
match c is Car:  # True
    ...
match c is CarA:  # True
    ...
match c is CarB:  # False
    ...
```

**Comment by auscompgeek** [comment]
> Current solutions: https://pypi.python.org/pypi/enum/0.4.6

Wrong package. The backport is the enum34 package on PyPI.

**Comment by auscompgeek** [comment]
The stdlib enum is a very complex beast. I've done things like:

```python
class Suit(Enum):
    def __str__(self):
        return chr(0x2660 + self.value)

    SPADES = 0
    HEARTS = 1
    DIAMONDS = 2
    CLUBS = 3

class Value(Enum):
    def __str__(self):
        if self is self.ACE:
            return 'A'
        if self is self.JACK:
            return 'J'
        if self is self.QUEEN:
            return 'Q'
        if self is self.KING:
            return 'K'
        return str(self.value)

    ACE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN = range(1, 11)
    JACK = 11
    QUEEN = 13
    KING = 14

class Card:
    __slots__ = 'suit', 'value'

    def __init__(self, value, suit):
        self.value = Value(value)
        self.suit = Suit(suit)

    def __str__(self):
        return chr(0x1F0A0 + (self.suit.value << 4) | self.value.value)

print(Card(2, Suit.CLUBS))  # Unicode character for 2 of clubs: 🃒
```

It would be a shame if this valid Python suddenly became incompatible with Coconut, if Coconut is supposed to be a superset of Python 3.

**Comment by ArneBachmann** [comment]
@evhub I still don't get the `match` syntax:
Where is the `in <value>` in your expression?
```
match <pattern> in <value> [if <cond>]:
    <body>
[else:
    <body>]
```

Also to be functional, match should be an expression, but I think there's an issue for that already.
```
a:str? = case value:
  match is int: "int"
  match is float: "float"
  else: None
```
or similar....

Regarding using `data` to model enums I think there must be a "physical" connection between the enum type and its variants (like `Enum.Variant`), but I don't understand how `CarA is Car` since `Car` is a tuple and `CarA` another object (?)

**Comment by evhub** [comment]
@ArneBachmann Whoops, forgot the case statement. My example should have been:
```python
case c:
    match _ is Car:  # True
        ...
    match _ is CarA:  # True
        ...
    match _ is CarB:  # False
        ...
```

**Comment by tbsexton** [comment]
@evhub , @ArneBachmann Sorry to dredge up an old-ish issue, but figured this was the only `Enum`-related open one. Thinking about  constructing `data` types as `Enum`-compatible, I would like to get your thoughts on integrating the `Enum` [functional-style API](https://docs.python.org/3/library/enum.html#functional-api) with the `data` keyword. 

Namely, I can currently call a function like `Animal = Enum('Animal', 'ANT BEE CAT DOG', module=__name__)` and that will create a "sum type" of sorts on the fly, which can be very useful. However, for the coconut ADT's I see your example 
"""
data Ant
data Bee
data Cat
data Dog
Animal = Ant, Bee, Cat, Dog
"""
means that it's rather difficult to see how this could be done on-the-fly. Of course, for hierarchical/complex datatypes I would like to use coconut's pattern-matching to build functions, and the immutability is a huge plus. 

My personal use case is similar to [this](https://stackoverflow.com/questions/50404640/representing-complex-objects-in-a-python-enum) where I need to build complex objects, but rather than limit the low-level "verb", "noun" identifiers, my users need to be able to subclass on the fly with custom types..i.e. I know the users will be dealing with cars, but will not know a-priori whether they want "car A" vs "car B" or "car Sedan" vs "car Truck", or "car green" vs "blue" vs "red" vs...etc. That information is taken in via json/yaml on a gui. But ultimately all cars will share some basic relationships/rules with other types (idk, tractors?), regardless of what the user supplies.

**Comment by auscompgeek** [comment]
In case anyone comes here looking for an enum backport, I've been informed that https://pypi.org/project/aenum/ is a maintained package that backports enum with enum.Flag as well.

**Comment by evhub** [comment]
As of `coconut-develop>=1.5.0-post_dev82`, Coconut will turn `import enum` into `import aenum` on Python versions that don't support the standard library `enum` module (and `pip install coconut-develop[all]` or `pip install coconut-develop[enum]` will install `aenum`).
