### ISSUE TITLE
Improve documentation for type annotation for lists

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#353]
Currently we have the convention of `typename[]` for a `Sequence[typename]`.
This fails mypy in most cases, as it doesn't allow a direct assignment as in `data[index] = ...`.

I had to resort to `variable:List[type]` which seemed counter-intuitive as I assumed `[]` to be the most often used type annotation shortcut, but it was for `Sequence` instead instead of `List`.
Should we swap them or introduce a different shortcut? `[.]`

**Comment by evhub** [comment]
@ArneBachmann My rationale for using `Sequence` instead of `List` is that, if you're writing in a functional style, assignment should be rare, and tuples should be common. Thus, `Sequence` is a better default since it accommodates tuples and doesn't allow for assignment. That being said, I'm willing to be persuaded that that was a bad choice of default.

**Comment by ArneBachmann** [comment]
OK good, it´s probably my coding style or third party libraries that make it hard to pass `--mypy`.
Let´s add a better hint to the documentation and close this.
