### ISSUE TITLE
SyntaxError when applying a function inside a partial application

### ISSUE THREAD

**Issue by dileep-kishore** [evhub/coconut#355]
Coconut: Version 1.3.1 [Dead Parrot] running on Python 3.6.2

Parsing error occurs when the following is run:
```python
(|(1,2),(3,4),(5,6)|) |>  pd.DataFrame$(list(?), columns=['a','b'])
```

Works fine when I change it to:
```python
(|(1,2),(3,4),(5,6)|) |> list |>  pd.DataFrame$(?, columns=['a','b'])
```

Error:
```
coconut.exceptions.CoconutParseError: parsing failed (line 1)
  [(1,2),(3,4),(5,6)] |> iter |> pd.DataFrame$(list(?), columns=['a','b'])
  File "<string>", line unknown
SyntaxError: parsing failed
  [(1,2),(3,4),(5,6)] |> iter |> pd.DataFrame$(list(?), columns=['a','b'])
```

The above is a contrived example and the issue can be easily avoided as shown above. If this seems like something that coconut does not need to support then feel free to close this issue.

**Comment by evhub** [comment]
@dileep-kishore Coconut's question-mark partial application doesn't support arbitrary nesting since that would require making an arbitrary lambda instead of just a partial application object. The right way to do this in Coconut is exactly what you changed it to, where `list` is a separate function in the pipeline. My thinking is that you should be able to cover all the use cases for this if you just change it to that, and I think the pipeline-style is more explicit, since it lets you see more easily all the different functions being applied.

**Comment by dileep-kishore** [comment]
That makes sense.
