### ISSUE TITLE
Add implicit partially applied operator function syntax

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#36]
```
(< 5) => (lambda x: x < 5)
(5 +) => (lambda x: 5 + x)
```

**Comment by evhub** [comment]
```
(? < 5) => (lambda x: x < 5)
(5 + ?) => (lambda x: 5 + x)
```

**Comment by evhub** [comment]
```
($ < 5) => (lambda x: x < 5)
(5 + $) => (lambda x: 5 + x)
```

**Comment by evhub** [comment]
```
$( f(?) * 5 ) => (lambda _: f(_) * 5)
```

**Comment by evhub** [comment]
The suggestion is to use the `?` style syntax.

**Comment by evhub** [comment]
Additionally, we'd like to support any expression, so we'd have
```
(5 + f(?, 2))
```
is the same as
```
((x) -> 5 + f(x, 2))
```

**Comment by evhub** [comment]
New syntax suggestion: since we need to know when the lambda starts, we'll use this:
```
(-> ? + 2)
```
as shorthand for
```
((x) -> x + 2)
```

**Comment by candeira** [comment]
What's the gain if you have to write the arrow?

Also, the other character which, with ?, is not currently in use by Python, is $. So Coconut could write anonymous functions in a manner analogous to Clojure's `#(str %)` syntax:

`$(1 + ?)` would be equivalent to `def (x) -> (1 + x)`
`$(? + ?2)` would be equivalent to `def (x, y) -> (x + y)`
`$(?1 + ?2)` would also be equivalent to `def (x, y) -> (x + y)`

But really, for readability and for historic reasons, I'd switch '$' and '?' around:

`?(1 + $)` would be equivalent to `def (x) -> (1 + x)`
`?($ + $2)` would be equivalent to `def (x, y) -> (x + y)`
`?($1 + $2)` would also be equivalent to `def (x, y) -> (x + y)

If you like this syntax, I'd be happy to try my hand at implementing it.

**Comment by candeira** [comment]
About the above: during the first pass at reading the docs, I had missed that `$` is already in use for partial application `$()` and iterator slicing `$[]`

I'd suggest changing that to `foo?(...)` and `foo?[...]`, because $ is so much better syntax for implicit positional variables, and the question mark works well for the suggested use too.

However, keeping the `functionname$()` for partial application and using the solitary `$()` for defining anonymous functions would also be compatible.

**Comment by evhub** [comment]
I like the
```
$( ? + 2 )
```
syntax, although I'm not sure about the
```
$( ?1 + ?2 )
```
syntax, since it's not nearly as obvious what's going on there just by looking at it. I think at that point just using `->` is the cleaner choice.

**Comment by vindarel** [comment]
I like very much the `(-> ? + 2)` suggestion :) 

But why is `( < 2)` , your first suggestion, eliminated ? That's very elegant, the shortest (and what I'm used to with [livescript's functional library](http://www.preludels.com/#obj-filter)).
Chaining transformations like that is a joy, there's nothing redundant, what's in there matters:
```livescript
[ { id: 1, title: ""}... ]
|> filter(.id > 3)  
|> sort-by(.title)  
```

instead of 
```livescript
[ {...}]
|> filter( -> ?.id > 3) # or ?['id']
|> sort-by( -> ?.title)
```
which is pretty good also :)

**Comment by candeira** [comment]
Yeah, the only reason I suggested `$(?1 + ?2)` was to mirror Clojure, which allows any number of implicit numbered params. However, I agree that at that point using the arrow syntax is better.

**Comment by fredcallaway** [comment]
We should consider parsing. How do we know if `(1 + (sqrt($ + 1)))` is one big function or an expression where 1 is being added to a function? I'd rather avoid a prefix symbol, but it may be necessary.

**Comment by evhub** [comment]
@candeira @vindarel @fredcallaway Here are the options for this that I am considering implementing:

1. `(-> f(?) + 5)`
 - pros: looks similar to the existing `->` lambda syntax
 - cons: uses a lot of symbols which makes it hard to read
2. `(> 5)`
 - pros: clean, simple, concise, probably the best-looking syntax
 - cons: not a full lambda syntax, only supports the partial application of a single operator, since to detect when the lambda starts I would look for an operator at the beginning or end of the parenthetical
3. `$(f(?) + 5)`
 - pros: looks similar to the existing `$` partial application syntax, which makes sense, since a lambda is basically just a partial application for an expression
 - cons: could be confused with the existing `$` partial application syntax, uses a lot of symbols which makes it hard to read

Is there any consensus on which of these you would prefer?

**Comment by vindarel** [comment]
My humble preference:

- I would ditch n°3 because I'm not used to this syntax and I'm sure I'll be confused with partial application
- 1- is ok, quite good
- 2- would be my favourite but I'm unsure, there may be a big limitation in the proposal: will we have to write an operator just by a parenthesis ? If so, how could we apply a transformation to, say, a list of dicts where we want to check a given key ? Like 

`( (x) -> x['id'] > n)` 
could we do `(.get('id') > n)` ?

 (we would need to access the key on the other side of the operator, and the operator would not be close to a parenthesis any more). Maybe there's a Coconut trick I don't know (quite new to it).
- 2- is ok, if we need a more complicated lambda with more than one argument, it's a less usual case, so we can as well write a full lambda `( (x, y) -> ... )`

Thx for asking :)

**Comment by evhub** [comment]
@vindarel Thanks for the input! I think I'm currently leaning towards 1, and that will probably be what gets implemented in the next release.

**Comment by evhub** [comment]
Slight alteration—because I'd rather have the implicit lambda argument be a valid Python identifier, I'm thinking of using `_` instead of `?`. Any comments on whether `_` is better / worse / same as `?`?

**Comment by vindarel** [comment]
At first glance, that could be counter-intuitive because _ is commonly used to ignore that value (in python it's just a convention, but it is really ignored by some languages, no ?), and even more in Django we are encouraged to do

    from django.utils.translation import ugettext as _

**Comment by fredcallaway** [comment]
Most importantly, _ is a valid variable name so using it as a keyword could break valid Python code.

Cheers,
Fred
--

**Comment by evhub** [comment]
@vindarel @fredcallaway It wouldn't be used as a keyword, and it wouldn't at all overlap with the way it is used to ignore values. My suggestion is just that
```
(-> "hello")
(-> _[0])
```
should compile to
```
(lambda _=None: "hello")
(lambda _=None: _[0])
```
which allows the implicit lambda syntax to be used both for 0 argument and 1 argument lambdas, makes it so that the valid variable name rules stay the same as in Python, and shouldn't break any valid Python code.

**Comment by fredcallaway** [comment]
@evhub 
Fair enough. A remaining problem is that this would shadow an existing `_` variable. I'm tempted to say that this is an okay tradeoff because the `_` syntax is the most intuitive for me.

Glad to hear that it's already in development! 👍

**Comment by evhub** [comment]
@fredcallaway The advantage of `_` being the variable that is shadowed is that the Python convention is not to use `_` for variables you actually want to access. Therefore, theoretically, you shouldn't need to access an outer `_` from inside the lambda if you're following the Python idiom.

**Comment by evhub** [comment]
This is live in develop now, so I'm closing this ticket.

**Comment by evhub** [comment]
In addition to implicit lambdas as was implemented here, I think it would also be a good idea to add implicit operator functions using the `(? + 5)` syntax, which would be equivalent to `(+)$(?, 5)`, since I think the former is a lot easier to read. Reopening this issue to add that syntax.

**Comment by fredcallaway** [comment]
I like this. But if you add this, why not go all the way and allow `(foo(?, 5))`

**Comment by evhub** [comment]
@fredcallaway The syntax `(-> _ + 5)` or `(-> foo(_) + 5)` was already added and handles those use cases. The rationale for `(? + 5)` is that it would generate a partially-applied operator function instead of a lambda, which is significantly better for pickling, casting to a str, profiling, etc.

**Comment by evhub** [comment]
Maybe the right solution is just to detect implicit lambdas of the form `(-> _ + 5)` and automatically compile them to partially-applied operator functions, but that seems too implicit and weird to me, so I'm wary to do it.

**Comment by evhub** [comment]
I am breaking this off into a separate issue, instead of resurrecting this long-closed one. See #258.
