### ISSUE TITLE
Python-universal code doesn't run on Python 2

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#373]
When running code via `coconut-run x.coco` it works, if run via `python2 x.py` it doesn't:
```
  File "sos/sos.py", line 10
    py_chr, py_filter, py_hex, py_input, py_int, py_map, py_object, py_oct, py_open, py_print, py_range, py_str, py_zip, py_filter, py_reversed, py_enumerate = chr, filter, hex, input, int, map, object, oct, open, print, range, str, zip, filter, reversed, enumerate
```

with `x.py`:
```
print("Hello")
```

However. `python2 x.coco` works fine, it maybe reads out the shebamg...

**Comment by evhub** [comment]
@ArneBachmann When using Coconut, you need to pass in the name of the Coconut file, not the compiled Python file. Try `coconut-run x.coco` instead.

**Comment by ArneBachmann** [comment]
That's what I accidentally discovered. But it reads the shebang, I believe, which again refers to /usr/bin/ Python3, or am I mistaken?

**Comment by evhub** [comment]
@ArneBachmann The issue is just that Coconut will not (and should not) accept as input its own compiled output.

**Comment by ArneBachmann** [comment]
I guess this is a misunderstanding. What I mean is that coconut is a source-to-source transpiler.
But the transpiled Python-universal code is simply not executable by Python2.7 and I think it's a bug.
I'm not talking about executing `*.py` via coconut.
I also corrected my initial comment above which had a little typo.

**Comment by evhub** [comment]
@ArneBachmann Ah. I see the problem. `coconut-run` implicitly assumes `--target sys`, and since Coconut is running on Python 3, that means `x.py` gets compiled with `--target 3`, so it's not suitable for being run on Python 2. Just compile the file using `coconut` instead and all will be fine. If you really want to produce universal code with `coconut-run`, you can now pass `--target universal`, which will do what you want.

**Comment by ArneBachmann** [comment]
It worked!
**Note**: There is still no ` --target universal`, only leaving out the ` --target`  switch allows to compile to universal code.
