### ISSUE TITLE
Support generator expressions inside `zip`

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#378]
I stumbled over an undefined syntax error. It turned out, that using a generator expression doesn't get treated like an implicit list in `zip(a for a in b, c for c in d), as it does inside `any(a for a in b)` which gets interpreted like `any([a for a in b])` automatically, as of Python 3. Took me a while to determine the root cause.

**Comment by evhub** [comment]
@ArneBachmann That's because generator expressions must be surrounded by parentheses. As a convenience to avoid double parentheses, Python allows those parentheses to be the same as the parentheses used to call a function, but otherwise, you really must surround your generator expressions in parentheses. This is all just Python stuff, and there isn't really any alternative because anything else creates ambiguity. For example, consider `zip(a for a in x, y, z for b in b)`. What does that mean? There are a bunch of different possibilities:

- `zip( (a for a in x, y), (z for b in b) )`,
- `zip( (a for a in x), (y, z for b in b) )`, or
- `zip( (a for a in x), y, (z for b in b) )`.

I think any choice from the above would create confusion.

**Comment by ArneBachmann** [comment]
Thanks for the explanation! I've been working with Python for years, but there's always something new to learn... Is zip with generators lazy (in the sense of processing items on the go)? Will test it.
