### ISSUE TITLE
Add implicit -> None type annotation to __init__ methods

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#389]
Should work fine with mypy even if not marked via `-> None:` (because it's implicit in Python terms)

**Comment by eindiran** [comment]
What args are you passing to mypy? I am asking because I just compiled an example without an annotation and ran mypy with my standard set of mypy args, and I did not see a warning.

My standard mypy args: '--ignore-missing-imports', '--python-version', '3.5', '--warn-incomplete-stub', '--warn-redundant-casts', '--warn-return-any', '--warn-unused-ignores'

**Comment by evhub** [comment]
@ArneBachmann I can't replicate this; can you give me some example code that replicates this error?

**Comment by ArneBachmann** [comment]
I don't use any of those mypy options, but it seems to have gone away, was probably earlier a thing with Python 2 code compat problems, that made me make it a habit to mark every procedure with -> None. I recently decided to ditch all Python 2 support as it was really hard to achieve, even with Coconut. Just wasn't worth it anymore, especially since any reliable Python console app on Windows requires PEP528/529, supported only from Python 3.6 on (!).

**Comment by ArneBachmann** [comment]
I have it again:
```
sos/utility.py:65: error: The return type of "__init__" must be None
```

for
```
def __init__(_, mapping:Dict[str,Any]): dict.__init__(_, mapping)
```

Any idea?

**Comment by auscompgeek** [comment]
`__init__` must always be annotated with a return type of None, as per PEP 484. Not a bug.

**Comment by eindiran** [comment]
That's not entirely correct. PEP 484 specifies that `__init__` should be annotated with a return type of `None` if annotated, but that "Python will remain a dynamically typed language, and the authors have no desire to ever make type hints mandatory, even by convention".

As you can see in [this mypy issue](https://github.com/python/mypy/issues/604), Guido himself complains that "... it'd suck if we'd have to develop the habit of adding explicit '-> None' to all **init** methods just to make mypy happy". But the issue is still an open bug with mypy, so for the time being, making mypy happy requires that you explicitly add the '-> None'. Hopefully in the near future, `__init__` will be assumed to have a default return type of `None` instead of `Any`, as mentioned in the final comment.

**Comment by evhub** [comment]
One possible solution to this is to have Coconut automatically annotate `__init__` definitions with a return type of `None`. Thoughts?

**Comment by ArneBachmann** [comment]
+1 since also class definitions may leave out the : pass part, similar how -> None could be left out.

**Comment by auscompgeek** [comment]
Per the above, this is probably not worth implementing. If someone wants a type-checked no-argument `__init__`, then they should probably type hint the function signature.

If someone _didn't_ want their no-argument `__init__` type-checked, then that should still be possible whilst still running mypy on their code.
