### ISSUE TITLE
Add a TYPE_CHECKING constant

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#403]
Would be `False` at runtime and `True` during type checking similar to `typing.TYPE_CHECKING`. The only difference from `typing.TYPE_CHECKING` would be that it would be supported on all Python versions, including Python 2.

If this is implemented, it will likely also involve rolling back #383/#339, which would then resolve #396.

**Comment by evhub** [comment]
See <http://coconut.readthedocs.io/en/develop/DOCS.html#type-checking> for usage.

**Comment by ArneBachmann** [comment]
It seems you removed the automatic `from typing import *` during these refactorings, right? Probably makes sense

**Comment by evhub** [comment]
@ArneBachmann You should not be detecting the Coconut version in your code--there is absolutely no reason to do that since you should never be distributing uncompiled Coconut code. Instead, just compile your code on whatever version you prefer, then redistribute the compiled Python.

**Comment by ArneBachmann** [comment]
I know, and the assumption to distribute only Python code makes all easier.
However, as open source goes, I don´t have control over what build environments others might use, including uncontrolled versions of Coconut, my code, or Python. Maybe I´m trying to hard to work around all possibilities, but it feels necessary to me. I also transpile the Coconut code on the CI platforms instead of only testing the generated Python code (I don´t like putting generated code into repositories, and this way I can test the entire tool chain).
