### ISSUE TITLE
"or" pattern operator does not work properly with dict patterns of different nesting levels

### ISSUE THREAD

**Issue by arnauorriols** [evhub/coconut#464]
```
>>> match {"a": {"b": x }} = {"a": {"b": {"c": "x"}}}                                                                                                          
>>> x                                                                                                                                                          
{'c': 'x'}
>>> match {"a": {"b": {"c": x}}} = {"a": {"b": {"c": "x"}}}                                                                                                    
>>> x                                                                                                                                                          
'x'
>>> match {"a": {"b": x }} or {"a": {"b": {"c": x}}} = {"a": {"b": {"c": "x"}}}                                                                                
Traceback (most recent call last):
  File "/home/orriols/.virtualenvs/rancher-catalog-list-versions/lib/python3.7/site-packages/coconut/command/util.py", line 167, in exec_func
    exec(code, glob_vars)
  File "<string>", line 8, in <module>
NameError: name '_coconut_match_temp_2' is not defined
```

**Comment by evhub** [comment]
The problem appears to be the repeated `x` variable name. Coconut interprets the repeated `x` as asking for the two appearances of `x` to be equal, but since they appear in different branches of the `or`, the check that they in fact be equal fails.

As a temporary solution, you could just use `x` in one branch and `y` in the other, though obviously the more permanent solution should be to disable that behavior when the variables appear in different `or` branches.

**Comment by arnauorriols** [comment]
but then I wouldn't know if use `x` or `y` without incurring in a `referenced before assignment` error, right?

My real use-case is in a pattern-matching function, which I could workaround just writting separate functions for each `or` branch.

Kudos for the amazing job, I'm loving Coconut!

**Comment by evhub** [comment]
@arnauorriols @narfanar This should now be fixed in the latest `coconut-develop`! Just `pip install -U coconut-develop` to get the latest version.
