### ISSUE TITLE
Problem with the chain operator

### ISSUE THREAD

**Issue by hoishing** [evhub/coconut#478]
I got a `Segmentation fault: 11` error message when I try to run the follow code. 
```
a = [1,2]
b = [3,4]
a = a :: b
list(a)
```
if I use `a ::= b` instead, everything is fine. Any idea?

**Comment by evhub** [comment]
@hoishing Because `::` is lazy, it will run into issues if one of the variables it references lazily gets rebound later. In particular, if it gets rebound like this to the very iterator it is referenced in, it will trigger a segmentation fault (it's a [known Python issue](https://bugs.python.org/issue14010)). Because the Coconut compiler is aware of this issue, it will carefully compile `a ::= b` to
```python
temp = a
a = temp :: b
```
to get around the issue. If you don't want to use `::=`, you can just do the same thing and create a temp variable like the above.
