### ISSUE TITLE
Multiple no-arg lambda functions use same variable name (underscore)

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#479]
I'm having trouble creating a minimal example, but having several optional-arg lambdas `-> something (-> something-more))` in one line of code reuses/redefines the underscore variable name in the compiled Python code which sometimes seems to breaks my code.

**Comment by evhub** [comment]
No-arg lambdas aren't really meant to be used that way. The purpose of no-arg lambdas is to provide a very convenient way of doing something very simple like `-> _**2`, not to do something complicated that would require nesting them inside each other. I think it's fine if you can't really use no-arg lambdas inside each other because at that point you should just give the argument a name.

**Comment by Sitwon** [comment]
Can you provide an example that demonstrates `-> something (-> something-more)` behaving differently than `(_=None) -> something ((_=None) -> something-more)`?

**Comment by ArneBachmann** [comment]
There you go:

```python
import codecs

CODEC_FUNCTIONS:List[str] = ['utf_32_be', 'utf_32_le', 'utf_32', 'utf_16_be', 'utf_16_le', 'utf_16', 'utf_7', 'utf_8_sig', 'utf_8']

def tryOrDefault(func:Callable[[], Any], default:Any) -> Any:
  try: return func()
  except: return default

binary:bytes = "sldjäöü".encode("utf-8")
decoded:FrozenSet[str] = frozenset(filter(-> tryOrDefault(() -> codecs.encode(codecs.decode(binary, _),_) == binary, None), CODEC_FUNCTIONS))

print(decoded)
```
Note how the filter requires a lambda, which uses a function with a lambda that uses the outer lambda argument.

**Comment by Sitwon** [comment]
@ArneBachmann You've provided an example, of where you might nest one lambda within another, but if you were to rewrite both lambdas in the `(_=None) -> expression` form then it would become clear why the variable `_` has a different definition in different parts of the line.

Consider the following:
```python
>>> x = -> print( repr(_), repr( ( -> (_))() ) )                                                                                                            
>>> x('a')                                                                                                                                                  
'a' None
>>> x = -> print( repr(_), repr( (() -> (_))() ) )                                                                                                          
>>> x('a')                                                                                                                                                  
'a' 'a'
>>>
```

As we know from the documentation the first line `x = -> print( repr(_), repr( ( -> (_))() ) )` literally translates to `x = (_=None) -> print( repr(_), repr( ((_=None) -> (_))() ) )`. So the behavior is exactly what we would expect.

You have proposed that the line should be dynamically composed something like `x = (_=None) -> print( repr(_), repr( ((_1=None) -> (_))() ) )`, however I would find that much harder to reason about. It would take a lot more mental gymnastics to keep track of your lambda nesting depth to correctly refer to each layer's implicit argument than it would to explicitly name any arguments you wish to use in a subsequent depth.

In your example, you solved it by explicitly defining the inner lambda to take no arguments. I would have instead recommended solving it by explicitly naming the argument to the first lambda.

```python
decoded:FrozenSet[str] = frozenset(filter((c) -> tryOrDefault(-> codecs.encode(codecs.decode(binary, c), c) == binary, None), CODEC_FUNCTIONS))
```

Not only does this make it clear that to which lambda the variable belongs, but it also makes it clear that the lambda is expecting one and exactly one argument (not optional).

**Comment by ArneBachmann** [comment]
Sure that's what I tried as well. I was just considering how you would cope with multiple implicit underscores when using the `(-> ...)` notation. Since the default argument is implicitly generated in the Coconut to Python conversion, I also wanted to use that convention.
The issue is simply that Coconut should not create code with nested same-named variables to avoid problems, or am I seeing that wrong?

**Comment by Sitwon** [comment]
As a programmer, I can look at a line like:
`( -> something(-> something_else))`
and translate it in my head to:
`((_=None) -> something((_=None) -> something_else))`

So I think it's just a matter of being aware that the no-parameter variant will literally translate to an implicit underscore, and then you expect that each nested level creates a new scope and overwrites the underscore.

If Coconut gave a unique name to each implicit variable, then the line above might translate as:
`((_1=None) -> something((_2=None) -> something_else))`
or it might translate as:
`((_5=None) -> something((_6=None) -> something_else))`

Just from that one snippet, out of context, you can't tell which. You need to look back and count the nesting depth to know what your implicit variable is named. Also, if you refactor your code and the nesting depth of your lambda changes, then you need to re-count and update the implicit variable name. 

Obviously, nesting lambdas 6 layers deep is probably an anti-pattern, but if pressed I'm sure I could contrive an example to demonstrate it.

My point is that the current syntax allows you to concisely consider _just_ the current expression. Your proposal would force you to consider the entire statement and the position of the expression within that statement. You would have to keep track of more state in your head while writing your expression.

If you need to share a variable between scopes, that variable probably deserves an intentional name.
Save the implicit variable for cases where you're using it only within the same scope.

**Comment by evhub** [comment]
@ArneBachmann @Sitwon I think I'm going to close this issue as a won't fix, under the rationale that no-arg lambdas aren't really built for nesting, and all the possible fixes I can think of only make no-arg lambdas more complicated.

**Comment by ArneBachmann** [comment]
I can follow your rationale. Probably it just needs a clear doc update in "Lambdas" after
*, and when one argument (assigned to `_`) is required.*:
"Note, that nesting several no-argument lambdas will lead to problems with the scope of the `_` parameters." or similar.

**Comment by evhub** [comment]
@ArneBachmann Yeah, that's probably a good idea. I'll change this to be a documentation issue.
