### ISSUE TITLE
Add do-while loops

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#569]
Possible syntaxes:
```python
do:
    ...
while cond
```

```python
do while cond:
    ...
```

```python
do:
    ...
while: cond
```

Regardless, they should be compiled to:
```python
while True:
    ...
    if not (cond):
        break
```

**Comment by Sitwon** [comment]
FWIW, the third syntax does not seem "Pythonic" to me. In existing control statements the condition goes before the colon, and the colon signals the start of a block. I think the first syntax seems the most intuitive, with the second syntax it might not be obvious how it's different from a normal "while" loop.

Is it possible to consider a different keyword, such as do/until or repeat/until instead of do/while to further distinguish it? (In the case of repeat/until, a 'repeat' without an 'until' could be a shorthand for 'while True'.)

I think your "should be compiled to" example was meant to be:
```python
while True:
    ...
    if not (cond):
        break
```

**Comment by rajpratyush** [comment]
is this issue open for work?

**Comment by evhub** [comment]
@rajpratyush No—I haven't decided on a good syntax for this yet.

**Comment by FelipeSharkao** [comment]
I don't know if this is really necessary. Coconut markets itself as a superset of python aimed for functional programming, where do-while doesn't fit that much. Anyhow, I'd vote for the this syntax, as it's much more readable:

```py
do:
    ...
while: cond
```
