### ISSUE TITLE
PEP 604: support for `Union` types as `X | Y`

### ISSUE THREAD

**Issue by tbsexton** [evhub/coconut#571]
This [will be added as a feature in Python 3.10](https://www.python.org/dev/peps/pep-0604/). I actually thought this was already in the `enhanced type annotation` section, but noticed coconut currently only does this kind of thing for optionals and callables. 

Would definitely love to see this new syntax added to coconut, especially as I've been writing more and more pydantic data-structures. One step closer to "elm-as-python" :D

**Comment by evhub** [comment]
@tbsexton This is a bit tricky, since there's no way for Coconut to just patch `type.__or__`. Thus, we'd have to do the same thing as the other enhanced type annotations, and just dynamically compile `|` to `Union` based on whether it's in a type annotation, except that the reason that this wasn't done earlier is that `|` already has meaning in Python, even inside of type annotations. So, for example, this would no longer work:
```python
def f(x: 1 | 2) = x
```
Since that would never work as a type annotation anyway, it's probably fine, but there are some cases where type annotation syntax is used for things other than type annotations, so this might break that. I think it's still probably a good idea to just implement this anyway, but there is that risk.

**Comment by tbsexton** [comment]
Meaning, patch to previous versions of python? Yeah I figured that may be problematic, though I wonder if a `__future__` import would be available... hmm.

**Comment by evhub** [comment]
To be clear, if you're running your compiled Coconut on a 3.10 version with this implemented, it will just straightforwardly work, no changes needed—the only sense in which this needs to be added to Coconut as a feature is to get it to work across Python versions.

**Comment by evhub** [comment]
@tbsexton This should now work on `coconut-develop>=1.5.0-post_dev30`.
