### ISSUE TITLE
How much memory should it take to install?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [evhub/coconut#608]
I'm running a little server with 1 GB memory and at most 3 GB that it could use for swap space. (I'm not sure whether the swap algorithm actually uses everything available to it.) Whenever I run `pip install coconut` it gets swamped at the step that builds a wheel for cPyparsing, and dies with a `virtual memory exhausted: Cannot allocate memory` message. Coconut is the only thing I've installed with pip that behaves like that. Do you know what it requires?

**Comment by evhub** [comment]
[`cPyparsing`](https://github.com/evhub/cpyparsing) installation requires running the [Cython](https://cython.org/) compiler, which is presumably what's taking up so much memory. If you're fine with just using vanilla `pyparsing`, you can just `pip install --upgrade --no-deps coconut pyparsing<3` and it should work. You could also try precompiling a `cPyparsing` binary for your machine.

Really, though, the long-term solution to this problem is to build precompiled [`manylinux`](https://github.com/pypa/manylinux) wheels for `cPyparsing`, which I haven't done yet.

**Comment by JeffreyBenjaminBrown** [comment]
Good to know. Thanks, Evan!
