### ISSUE TITLE
Error handling similar to Rust?

### ISSUE THREAD

**Issue by MarkuBu** [evhub/coconut#782]
I recently found Coconut and I think it is an interesting option for functional languages.

But I miss one Feature (at least I haven't found any hint for that). I'm looking for error handling similar to Rust with Result Type and Option Type.

In the factorial example in the interactive tutorial traditional exception handling is used for error handling (raise TypeError).

Did I miss something? If not, would it be a feature that should be added?

**Comment by evhub** [comment]
Yes; Coconut has this now! It was just added relatively recently, which is why it's not in the tutorial. What you're looking for is Coconut's [`safe_call`](https://coconut.readthedocs.io/en/latest/DOCS.html#safe-call) function and [`Expected`](https://coconut.readthedocs.io/en/latest/DOCS.html#expected) built-in.
