### ISSUE TITLE
Installation sous Windows

### ISSUE THREAD

**Issue by pcharbon70-leco** [evhub/coconut#850]
Good afternoon, 
I am having some issues installing Coconut on a windows 11 machine. 

The c++ linker throws a bunch of error about missing objects during the installation CPyparsing library.
<img width="741" alt="image" src="https://github.com/user-attachments/assets/fa02d486-38ee-4d01-89bd-1f3a2bc2ead3">

Is this a known issue and is there a known solution? My Googling magic seems to have failed me today.

**Comment by evhub** [comment]
Have you installed the [Microsoft Visual C++ Build Tools](https://stackoverflow.com/questions/40504552/how-to-install-visual-c-build-tools)? They're necessary for compiling `cPyparsing`. Alternatively, you can [do a vanilla Python installation using `conda`](https://coconut.readthedocs.io/en/latest/DOCS.html#using-conda)—compilation will be substantially slower but it should otherwise work fine.

**Comment by evhub** [comment]
Certainly you can mix Coconut with any Python GUI framework that you want, yes.
